#!/usr/bin/env python3.7
# Mark Saad
# Graph for wttr.in data based on airport code 

import os
import sys
import json
import urllib.request, urllib.parse, urllib.error

url = 'http://wttr.in/%s?format=j1'

code = os.environ.get('code', sys.argv[0][(sys.argv[0].rfind('_') + 1):])

if code == None: sys.exit(1)

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
        print("yes")
elif len(sys.argv) == 2 and sys.argv[1] == "config":
        print('graph_title Weather in %s' % code)
        print('graph_vlabel Temperature and Humidity')
        print('graph_category sensors')

        print('temperature.label Temperature F')
        print('temperature.draw LINE2')
        print('feel.label Feels Like Temperature F')
        print('humidity.label Humidity')

        print('graph_args --base 1000 -l 0')
else:
        u = urllib.request.urlopen(url % code)
        raw_data = u.read()
        encoding = u.info().get_content_charset('utf-8')
        u.close()
        json_data = json.loads(raw_data.decode(encoding))

        temp  = (json_data["current_condition"][0]["temp_F"])
        feel = (json_data["current_condition"][0]["FeelsLikeF"])
        hum = (json_data["current_condition"][0]["humidity"])
        print('temperature.value %s' % temp)
        print('feel.value %s' % feel)
        print('humidity.value %s' % hum)
